/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { KnowledgeEntryView, KnowledgeSkipView } from '@deepseek-ai/dsh-api-knowledge-controller/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6b6e6f776c65646765 {
    ingest: (filename: string, data: string, title: string | undefined) => Promise<RemoteResult<{ ingested: KnowledgeEntryView[]; skipped: KnowledgeSkipView[]; }>>
    list: () => Promise<RemoteResult<KnowledgeEntryView[]>>
    removeDocument: (id: string) => Promise<RemoteResult<{ removed: boolean; }>>
  }
  interface TypertRemoteMap {
    'knowledge/ingest': (filename: string, data: string, title: string | undefined) => Promise<RemoteResult<{ ingested: KnowledgeEntryView[]; skipped: KnowledgeSkipView[]; }>>
    'knowledge/list': () => Promise<RemoteResult<KnowledgeEntryView[]>>
    'knowledge/removeDocument': (id: string) => Promise<RemoteResult<{ removed: boolean; }>>
  }
  interface TypertRemoteNamespaceMap {
    'knowledge': TypertRemoteNamespace$6b6e6f776c65646765
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
