/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_0$schema = z.string()
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_1$schema = z.string()
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_2$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_result$schema = z.object({
  'ingested': z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'filename': z.string().readonly(),
  'format': z.union([z.literal("text"), z.literal("markdown"), z.literal("html"), z.literal("pdf"), z.literal("docx")]).readonly(),
  'path': z.string().readonly(),
  'chunkCount': z.number().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
})),
  'skipped': z.array(z.object({
  'path': z.string().readonly(),
  'reason': z.string().readonly(),
})),
})
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_list_result$schema = z.array(z.object({
  'id': z.string().readonly(),
  'title': z.string().readonly(),
  'filename': z.string().readonly(),
  'format': z.union([z.literal("text"), z.literal("markdown"), z.literal("html"), z.literal("pdf"), z.literal("docx")]).readonly(),
  'path': z.string().readonly(),
  'chunkCount': z.number().readonly(),
  'createdAt': z.number().readonly(),
  'updatedAt': z.number().readonly(),
}))
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_removeDocument_parameter_0$schema = z.string()
const _deepseek_ai_dsh_api_knowledge_controller_knowledge_removeDocument_result$schema = z.object({
  'removed': z.boolean(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-api-knowledge-controller',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/ingest',
      service: 'knowledgeController',
      namespace: 'knowledge',
      method: 'ingest',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'filename',
          wire: 'filename',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/ingest:filename',
            schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_0$schema,
          },
        },
        {
          name: 'data',
          wire: 'data',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/ingest:data',
            schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_1$schema,
          },
        },
        {
          name: 'title',
          wire: 'title',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/ingest:title',
            schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_parameter_2$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/ingest:result',
        schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_ingest_result$schema,
      },
      sourceLocation: {"file":"packages/api/knowledge-controller/src/index.ts","line":94,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/list',
      service: 'knowledgeController',
      namespace: 'knowledge',
      method: 'list',
      invocation: { kind: 'direct' },
      parameters: [
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/list:result',
        schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_list_result$schema,
      },
      sourceLocation: {"file":"packages/api/knowledge-controller/src/index.ts","line":79,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/removeDocument',
      service: 'knowledgeController',
      namespace: 'knowledge',
      method: 'removeDocument',
      invocation: { kind: 'direct' },
      parameters: [
        {
          name: 'id',
          wire: 'id',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/removeDocument:id',
            schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_removeDocument_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-api-knowledge-controller#knowledge/removeDocument:result',
        schema: _deepseek_ai_dsh_api_knowledge_controller_knowledge_removeDocument_result$schema,
      },
      sourceLocation: {"file":"packages/api/knowledge-controller/src/index.ts","line":119,"column":9},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host service backing the generated `ctx.remote.knowledge` namespace. The `ctx.knowledge` read stays optional so a composition without the document-library provider still serves every other domain; each call reports the missing-provider diagnostic.",
        "summary": "Host service backing the generated `ctx.remote.knowledge` namespace.",
        "tags": [],
        "jsDoc": "/**\n * Host service backing the generated `ctx.remote.knowledge` namespace. The\n * `ctx.knowledge` read stays optional so a composition without the\n * document-library provider still serves every other domain; each call reports\n * the missing-provider diagnostic.\n */",
        "key": "knowledgeController",
        "exportName": "KnowledgeController",
        "members": [
          {
            "kind": "method",
            "name": "list",
            "signature": "@Remote async list(): Promise<KnowledgeEntryView[]>",
            "summary": "List every library document, newest first.",
            "jsDoc": "/**\n * List every library document, newest first.\n * @returns every stored entry as its wire view.\n */"
          },
          {
            "kind": "method",
            "name": "ingest",
            "signature": "@Remote async ingest( filename: string, data: string, title: string | undefined, ): Promise<{ ingested: KnowledgeEntryView[]; skipped: KnowledgeSkipView[] }>",
            "summary": "Upload one document into the library.",
            "jsDoc": "/**\n * Upload one document into the library. The host decodes `data` (canonical\n * base64), and the store persists the bytes inside the library it owns and\n * ingests that file — uploading the same filename again replaces the entry.\n * @param filename - client-reported filename including extension.\n * @param data - the file bytes as canonical base64.\n * @param title - optional display title overriding the file basename.\n * @returns the ingested entries and skipped candidates.\n */"
          },
          {
            "kind": "method",
            "name": "removeDocument",
            "signature": "@Remote async removeDocument(id: string): Promise<{ removed: boolean }>",
            "summary": "Remove one document and its chunks permanently.",
            "jsDoc": "/**\n * Remove one document and its chunks permanently. Idempotent: removing an\n * absent id succeeds with `removed: false`.\n * @param id - library identity returned by `list` or `ingest`.\n * @returns whether a document was removed.\n */"
          }
        ],
        "types": [
          {
            "name": "KnowledgeEntryView",
            "declaration": "export interface KnowledgeEntryView {\n    readonly id: string;\n    readonly title: string;\n    readonly filename: string;\n    readonly format: KnowledgeFormat;\n    readonly path: string;\n    readonly chunkCount: number;\n    readonly createdAt: number;\n    readonly updatedAt: number;\n}"
          },
          {
            "name": "KnowledgeFormat",
            "declaration": "export type KnowledgeFormat = 'text' | 'markdown' | 'html' | 'pdf' | 'docx';"
          },
          {
            "name": "KnowledgeSkipView",
            "declaration": "export interface KnowledgeSkipView {\n    readonly path: string;\n    readonly reason: string;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
